services:
  server:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    hostname: server
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./server
        target: /home/app
        read_only: false
      - type: volume
        source: node_modules_volume
        target: /home/app/node_modules
    depends_on:
      - mediamtx
    environment:
      - NODE_ENV=development
      - MEDIAMTX_HOST=mediamtx
    networks:
      - tfg-network
    
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtxTFG
    restart: unless-stopped
    ports:
      - "1935:1935"      # RTMP
      - "8554:8554"      # RTSP
      - "8888:8888"      # HLS HTTPS
      - "8889:8889"      # WebRTC HTTPS
      - "8189:8189/udp"  # WebRTC ICE/UDP
      - "9997:9997"      # API HTTPS
    volumes:
      - type: bind
        source: ./mediamtx/mediamtx.yml
        target: /mediamtx.yml
        read_only: false
      - type: bind
        source: ./server/key.pem
        target: /server.key
        read_only: true
      - type: bind
        source: ./server/cert.pem
        target: /server.crt
        read_only: true
      - type: bind
        source: ./mediamtx/recordings
        target: /recordings
    networks:
      - tfg-network

networks:
  tfg-network:
    driver: bridge

volumes:
  node_modules_volume: